### ISSUE TITLE
RabbitMq is broken for M1 chips

### ISSUE THREAD

**Issue by Lucrezia-Cester** [GSTT-CSC/hazen-web-app#101]
RabbitMQ doesn't work for M1 chip at the moment [https://stackoverflow.com/questions/10347751/rabbitmq-refusing-to-start](https://www.codementor.io/redirect-notice?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F10347751%2Frabbitmq-refusing-to-start)

To close this issue both of these actions shall be done:

-use docker for all of hazen-app (we already have a branch for this)
-use rabbitMQ on docker (add instructions on README)

**Comment by tomaroberts** [comment]
Closing as per #102
