### ISSUE TITLE
Verify hazen Tasks are working in hazen-web-app

### ISSUE THREAD

**Issue by tomaroberts** [GSTT-CSC/hazen-web-app#110]
Many of the hazen Tasks are performed on a single DICOM file. However, some of them require different inputs. For example, the `snr` task requires two files and the `slice_position` task requires a folder of DICOMs. 

It's not very intuitive to the user how the different tasks are run. To improve this, I propose we establish how each Tasks functions currently and then we can raise separate Issues and refine from there.

Can we fill out the table below to verify and track the development status of each Task.

**Edit – 06/09/23 – updated table with findings from Sophie's comment below.**

| Task | Input | Discussion | Linked Issue |
| ----------- | ----------- | ----------- | ----------- |
| acr_geometric_accuracy |  Requires a series of 11 images | :white_check_mark: – works well – can select one series with 11 images and the Task runs on the correct image. |       |
| acr_ghosting |  Requires a series of 11 images | :white_check_mark: – works well – can select one series with 11 images and the Task runs on the correct image. |       |
| acr_slice_position | Requires a series of 11 images | :white_check_mark: – works well – can select one series with 11 images and the Task runs on the correct image. |       |
| acr_snr | Requires a series of 11 images | :white_check_mark: – works well – can select one series with 11 images and the Task runs on the correct image.  |  --subtract with a second series (set of 11 images) is not currently supported   |
| acr_uniformity | Requires a series of 11 images | :white_check_mark: – works well – can select one series with 11 images and the Task runs on the correct image. |       |
| ghosting |  Single or multiple DICOM file(s) | :white_check_mark: – works well – can select both one or multiple series and the Task runs on all.|       |
| relaxometry |       |       |       |
| slice_position |    exactly 60 DICOM files | :white_check_mark: – works well – can select one series with 60 images and the Task runs.  |   #115 |
| slice_width |    Single or multiple DICOM file(s)   |    :white_check_mark: – works well – can select one or multiple series and the Task runs on all   |       |
| snr | Two DICOM files located in the same folder | :white_check_mark: – works well – can select one or multiple series and the Task runs on all. In hazen-web-app, the two uploaded files are listed as separate entries in the Workbench, which is unintuitive.  | #75 I think the user provided --measured_slice_width is not currently used |
| snr_map |   Single or multiple DICOM file   |  :white_check_mark: – works well – can select one or multiple series and the Task runs on all   |    needs a little tweak in routes.py near line 270   |
| spatial_resolution |    Single or multiple DICOM file   |  :white_check_mark: – works well – can select one or multiple series and the Task runs on all   |       |
| uniformity | Single or multiple DICOM file(s) | :white_check_mark: – works well – can select both one or multiple series and the Task runs on all. | N/A |

**Comment by tomaroberts** [comment]
Thanks for above Sophie.

One thing:

> celery -A hazen.worker worker -l INFO -P solo

Does this need to go into the setup documentation?

**Comment by sophie22** [comment]
Ideally not,`-P solo` essentially removes the async aspect of Celery which is not what we want long term. I will have to read more around the Celery documentation to understand how better to send workload to the Celery worker and get status updates, this is only temporary to check that the implementation of hazenlib and its tasks can work as intended.
the async aspect should be restored prior to deployment.
