### ISSUE TITLE
Slice Position task needs a folder of dicoms 

### ISSUE THREAD

**Issue by Lucrezia-Cester** [GSTT-CSC/hazen-web-app#115]
Slice_position function needs to take a folder as input. 

Currently our upload button only allows to upload files singularly, but the slice_position wants the user to select a single folder, rather than many files that make the folder. Currently, one cannot upload a folder with our upload button, this functionality needs to be implemented.

In the implementation of the solution I am updating the uploading button to allow it to upload a folder.

**Comment by sophie22** [comment]
Slice_position function needs to take exactly 60 input files. Files may be uploaded 'individually' and the series of 60 files selected as the input to the slice position task. There is no need to upload a folder as long as all the files within are uploaded.
