### ISSUE TITLE
Update contributors page in documentation

### ISSUE THREAD

**Issue by heyhaleema** [GSTT-CSC/hazen-web-app#37]

**Comment by tomaroberts** [comment]
@heyhaleema – is this still relevant?

Does it refer to this file?: https://github.com/GSTT-CSC/hazen-web-app/blob/main/docs/source/contributors.rst

Is it intended to be hazen-web-app contributors, hazen contributors or both? Would it make sense to use the [CITATION.cff](https://github.com/GSTT-CSC/hazen/blob/main/CITATION.cff) file in hazen as single source of truth?
