### ISSUE TITLE
Add selection icon to Workbench HTML table

### ISSUE THREAD

**Issue by tomaroberts** [GSTT-CSC/hazen-web-app#53]
Implement some kind of tick icon for the Workbench HTML table

**Comment by Lucrezia-Cester** [comment]
Hi @tomaroberts, It seems to me tables already have ticks. 
<img width="1295" alt="Screenshot 2023-01-27 at 08 52 41" src="https://user-images.githubusercontent.com/83493021/215046256-85fe926b-cae5-41d2-9ac6-ae1b7cb6c22c.png">


What do you mean by adding a tick icon?

**Comment by tomaroberts** [comment]
Implemented, so closing.
