### ISSUE TITLE
Some docstrings not rendering on website documentation

### ISSUE THREAD

**Issue by rs-sprout98** [GSTT-CSC/hazen-web-app#64]
Minor issue. As mentioned on Tuesday, some of the docstrings are not loading on the website. They are in slice_width.py in hazenlib on lines 38, 88, 124 and 594. The first and last are under function definitions whereas the middle two aren't (I'm assuming they might not display on purpose).

**Comment by tomaroberts** [comment]
Closing as superseded by #76 as mentioned above.
