### ISSUE TITLE
Desciption of each task is no longer pulled from docstring 

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen-web-app#76]
Previously with the old hazenlib the docstrings were pulled by the webapp to provide an overview of the task. This is no longer happening with the new hazenlib.

e.g. for slice_position

![image](https://user-images.githubusercontent.com/33687657/180444222-ba8713a1-c841-4fcb-856b-128e9a740069.png)

**Comment by sophie22** [comment]
I'm happy to have a discuss around how we want to communicate to the users what each of the available tasks can do and what sort of input they require. I don't think automatically parsing the __doc__ from the module is the best way to do this.

**Comment by sophie22** [comment]
Task description will be described in the ReadTheDocs autogenerated from the hazenlib docstrings and additional descriptions by MR physicists to other users.
