### ISSUE TITLE
Batch process single task

### ISSUE THREAD

**Issue by heyhaleema** [GSTT-CSC/hazen-web-app#84]
It would be good to be able to select and batch process multiple, related* series for a single task, e.g. perform the uniformity test on several series at a time. 

** This is distinct from #75 where at least two series are required for the SNR task.

**Comment by tomaroberts** [comment]
This works for the uniformity Task – and possibly others – but we need to verify which Tasks it doesn't apply to. See here for tracker table: #110

**Comment by sophie22** [comment]
works well in [current version](https://github.com/GSTT-CSC/hazen-web-app/commit/701aabc40839e312668e51244ee40b60b8368602) of the app
